"""Bank Model

Revision ID: ffaf8468f96d
Revises: 650d851a1381
Create Date: 2023-11-26 02:15:32.714069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffaf8468f96d'
down_revision = '650d851a1381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('bank_code', sa.Integer(), nullable=True),
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banks')
    # ### end Alembic commands ###
